name: Build and deploy backend to Azure Web App - skurkab-backend

on:
  push:
    branches:
      - main
    paths:
      - 'starter-skurkab-api/**'
      - '.github/workflows/backend.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build backend
        run: dotnet build starter-skurkab-api/DittBackendProjekt.csproj --configuration Release

      - name: Publish backend
        run: dotnet publish starter-skurkab-api/DittBackendProjekt.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A9B086AB6E784D9986FB4C658F2ABF34 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3905CC30DFD444A498A4259D0920F6C5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20B41D6CD06C4D23AFB827A5BDC75336 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: skurkab-backend
          slot-name: Production
          package: .
